name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test

  analyze:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: github/codeql-action/init@v1
      with:
        languages: javascript
        config-file: ./.github/config/codeql.yml
    - name: Analyze
      uses: github/codeql-action/analyze@v1
